// Project2.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.



#include <iostream>
void createFibonacciSequence(int maxNumber, int buf[], int &bufPointer);
int ReturnSumOfEvenNumbersInArray(int ArrayToSum[], int& endPointer);

int main()
{
	int buffer[100];
	int bufferPointer=0;
	createFibonacciSequence(4000000, buffer, bufferPointer);
	for (int x = 0; x < bufferPointer-1; x++) {
		printf("%d\n",buffer[x]);
	}
	int sum=ReturnSumOfEvenNumbersInArray(buffer,bufferPointer);
	//createFibonacciSequence(buf,bufEndPointer,MaxNumber);
	printf("Sum of all even numbers is:%d\n",sum);
	printf("Finished");
}



void createFibonacciSequence(int maxNumber,int buf[],int &bufPointer) {

	int leftNumber = 1;
	int RightNumber = 1;
	int currentNumber=0;


	while (currentNumber < maxNumber) {
		currentNumber = leftNumber + RightNumber;
		buf[bufPointer] = currentNumber;
		bufPointer++;
		leftNumber = RightNumber;
		RightNumber = currentNumber;
	}
}

int ReturnSumOfEvenNumbersInArray(int ArrayToSum[],int &endPointer) {
	int sum = 0;
	for (int x = 0; x < endPointer;x++) {
		int currentArrayNumber = ArrayToSum[x];
		if(currentArrayNumber %2==0){
			sum = sum + ArrayToSum[x];
		}
	}
	return sum;
}
// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
